Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-20.04"
  config.ssh.insert_key = false

  config.vm.define "ui" do |ui|
    ui.vm.network "forwarded_port", guest: 3030, host: 8000
    ui.vm.network :private_network, ip: "10.0.0.10"
    ui.vm.hostname = "ui"
    ui.vm.provider "virtualbox" do |v|
      v.name = "ui"
    end
    ui.vm.provision "shell", path: "uiScript.sh"
  end

  config.vm.define "api" do |api|
    api.vm.network :private_network, ip: "10.0.0.11"
    api.vm.hostname = "api"
    api.vm.provider "virtualbox" do |v|
      v.name = "api"
    end
    api.vm.provision "shell", path: "apiScript.sh"
  end
end
